
product:
  id: "string"
  email:
    type: string
    primary_key: "true"
    generated_value: "true"
#  unit_price:
#    type: float
#    nullable: false
#  supplier:
#    type: one_to_one
#    entity: sales/supplier
