user:
  opts:
    lombok:
      data: true                    # @Data annotation
      builder: true                 # @Builder annotation
      equals_and_hashcode:
        only_explicitly_included: false  # Incluir todos los campos por defecto
        call_super: false                 # Para herencia
      to_string:
        only_explicitly_included: false  # Incluir todos los campos por defecto
        include_field_names: true        # Incluir nombres de campos
      constructors:
        no_args: true
        all_args: true

    jpa:
      entity: true
      table:
        name: users

  # Clave primaria
  id:
    type: string
    lombok:
    # No necesita configuración específica ya que only_explicitly_included: false
    jpa:
      primary_key: true
      generated_value:
        strategy: uuid
      column:
        name: user_id
        nullable: false

  # Campos básicos
  username:
    type: string
    required: true
    unique: true
    lombok:
    # No necesita configuración específica ya que only_explicitly_included: false
    jpa:
      column:
        max_length: 50
        min_length: 3
        nullable: false
        unique: true

  email:
    type: string
    required: true
    unique: true
    format: email
    lombok:
    # No necesita configuración específica ya que only_explicitly_included: false
    jpa:
      column:
        max_length: 100
        nullable: false
        unique: true

  password:
    type: string
    required: true
    lombok:
      exclude_from_toString: true         # Por seguridad
      exclude_from_equals_and_hashcode: true  # Por seguridad
    jpa:
      column:
        max_length: 255
        min_length: 8
        nullable: false

#  first_name:
#    type: string
#    required: true
#    lombok:
#    # No necesita configuración específica ya que only_explicitly_included: false
#    jpa:
#      column:
#        name: first_name
#        max_length: 50
#        nullable: false
#
#  last_name:
#    type: string
#    required: true
#    lombok:
#    # No necesita configuración específica ya que only_explicitly_included: false
#    jpa:
#      column:
#        name: last_name
#        max_length: 50
#        nullable: false
#
#  phone:
#    type: string
#    required: false
#    format: phone
#    lombok:
#    # No necesita configuración específica ya que only_explicitly_included: false
#    jpa:
#      column:
#        max_length: 20
#        nullable: true
#
#  birth_date:
#    type: date
#    required: false
#    lombok:
#    # No necesita configuración específica ya que only_explicitly_included: false
#    jpa:
#      column:
#        name: birth_date
#        nullable: true
#
#  is_active:
#    type: boolean
#    required: true
#    lombok:
#    # No necesita configuración específica ya que only_explicitly_included: false
#    jpa:
#      column:
#        name: is_active
#        nullable: false
#        default: true
#
#  created_at:
#    type: timestamp
#    required: true
#    lombok:
#    # No necesita configuración específica ya que only_explicitly_included: false
#    jpa:
#      column:
#        name: created_at
#        nullable: false
#        default: "CURRENT_TIMESTAMP"
#        updatable: false
#
#  updated_at:
#    type: timestamp
#    required: false
#    lombok:
#    # No necesita configuración específica ya que only_explicitly_included: false
#    jpa:
#      column:
#        name: updated_at
#        nullable: true
#        on_update: "CURRENT_TIMESTAMP"